# Generated by Django 2.2.16 on 2022-05-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        #('users', '0002_alter_user_first_name'),
        ('users', '0002_auto_20220511_2212'),
    ]

    operations = [
    ]
