# Generated by Django 2.2.16 on 2022-05-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220513_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=False, max_length=128, verbose_name='password'),
        ),
    ]
