# Generated by Django 2.2.16 on 2022-05-14 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220514_0303'),
    ]

    operations = [
    ]
