# Generated by Django 4.0.4 on 2022-05-11 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(),
        ),
    ]
