# Generated by Django 2.2.16 on 2022-05-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220516_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='titles', through='reviews.GanreTitle', to='reviews.Genre'),
        ),
    ]
