# Generated by Django 2.2.16 on 2022-05-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220516_2013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='scope',
            new_name='score',
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(related_name='titles', through='reviews.GanreTitle', to='reviews.Genre'),
        ),
    ]
