# Generated by Django 2.2.16 on 2022-05-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220517_0702'),
        ('reviews', '0006_auto_20220516_2150'),
    ]

    operations = [
    ]
