# Generated by Django 2.2.16 on 2022-05-18 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20220517_2111'),
        ('reviews', '0007_merge_20220517_2204'),
    ]

    operations = [
    ]
