# Generated by Django 2.2.16 on 2022-05-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220519_1454'),
        ('reviews', '0010_merge_20220518_1404'),
    ]

    operations = [
    ]
