# Generated by Django 2.2.16 on 2022-05-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_merge_20220520_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(through='reviews.GanreTitle', to='reviews.Genre'),
        ),
    ]
