# Generated by Django 3.2.13 on 2022-06-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_auto_20220521_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='name',
        ),
    ]
