# Generated by Django 3.2.13 on 2022-06-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_rename_text_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='text',
        ),
    ]
